version: '3.8'

services:
  # Backend API Service (Development)
  backend:
    build:
      context: .
      dockerfile: web/backend/Dockerfile
    container_name: contractquard-backend-dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src:/app
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./src:/app/src
      - ./web/backend:/app/web/backend
      - ./requirements.txt:/app/requirements.txt
    command: ["python", "-m", "uvicorn", "web.backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
    networks:
      - contractquard-network

  # Frontend Service (Development)
  frontend:
    image: node:18-alpine
    container_name: contractquard-frontend-dev
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./web/frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - contractquard-network

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: contractquard-redis-dev
    ports:
      - "6379:6379"
    command: redis-server
    restart: unless-stopped
    networks:
      - contractquard-network

networks:
  contractquard-network:
    driver: bridge
