[build]
builder = "DOCKERFILE"
dockerfilePath = "web/backend/Dockerfile"

[deploy]
startCommand = "./entrypoint.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { ENVIRONMENT = "production", DEBUG = "false" }
