[build]
builder = "DOCKERFILE"
dockerfilePath = "web/backend/Dockerfile"

[deploy]
startCommand = "python -m uvicorn web.backend.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { ENVIRONMENT = "production", DEBUG = "false" }
